<div class="eob-card">
    <div class="eob-card-head">
        <div>
            <div class="eob-card-title">Asset Information</div>
            <div class="eob-card-sub">Track asset identity, purchase details, assignment, and lifecycle status.</div>
        </div>
    </div>

    <form method="POST" action="{{ $action }}">
        @csrf
        @if($method !== 'POST')
            @method($method)
        @endif

        <div class="eob-card-body">
            <div class="eob-form-grid">
                <div class="eob-group">
                    <label class="eob-label">Asset Code</label>
                    <input type="text" class="eob-input" value="{{ $generatedAssetCode }}" readonly>
                    <div class="eob-help">Auto-generated by the system.</div>
                </div>
                <div class="eob-group">
                    <label class="eob-label">Asset Name <span class="eob-label-required">*</span></label>
                    <input type="text" name="asset_name" class="eob-input" value="{{ old('asset_name', $asset?->asset_name) }}" required>
                    @error('asset_name')<div class="eob-error">{{ $message }}</div>@enderror
                </div>
                <div class="eob-group">
                    <label class="eob-label">Category</label>
                    <input type="text" name="asset_category" class="eob-input" value="{{ old('asset_category', $asset?->asset_category) }}" placeholder="Laptop, Mobile, Monitor">
                    @error('asset_category')<div class="eob-error">{{ $message }}</div>@enderror
                </div>
                <div class="eob-group">
                    <label class="eob-label">Status <span class="eob-label-required">*</span></label>
                    <select name="asset_status" class="eob-select" id="assetStatusSelect" required>
                        @foreach($statusOptions as $value => $label)
                            <option value="{{ $value }}" @selected(old('asset_status', $asset?->asset_status ?? 'available') === $value)>{{ $label }}</option>
                        @endforeach
                    </select>
                    @error('asset_status')<div class="eob-error">{{ $message }}</div>@enderror
                </div>
                <div class="eob-group">
                    <label class="eob-label">Brand</label>
                    <input type="text" name="brand" class="eob-input" value="{{ old('brand', $asset?->brand) }}">
                    @error('brand')<div class="eob-error">{{ $message }}</div>@enderror
                </div>
                <div class="eob-group">
                    <label class="eob-label">Model</label>
                    <input type="text" name="model_name" class="eob-input" value="{{ old('model_name', $asset?->model_name) }}">
                    @error('model_name')<div class="eob-error">{{ $message }}</div>@enderror
                </div>
                <div class="eob-group">
                    <label class="eob-label">Serial Number</label>
                    <input type="text" name="serial_number" class="eob-input" value="{{ old('serial_number', $asset?->serial_number) }}">
                    @error('serial_number')<div class="eob-error">{{ $message }}</div>@enderror
                </div>
                <div class="eob-group">
                    <label class="eob-label">Location</label>
                    <input type="text" name="location" class="eob-input" value="{{ old('location', $asset?->location) }}" placeholder="Head Office / Admin Room">
                    @error('location')<div class="eob-error">{{ $message }}</div>@enderror
                </div>
                <div class="eob-group">
                    <label class="eob-label">Purchase Date</label>
                    <input type="date" name="purchase_date" class="eob-input" value="{{ old('purchase_date', optional($asset?->purchase_date)->format('Y-m-d')) }}">
                    @error('purchase_date')<div class="eob-error">{{ $message }}</div>@enderror
                </div>
                <div class="eob-group">
                    <label class="eob-label">Purchase Cost</label>
                    <input type="number" name="purchase_cost" step="0.01" min="0" class="eob-input" value="{{ old('purchase_cost', $asset?->purchase_cost) }}">
                    @error('purchase_cost')<div class="eob-error">{{ $message }}</div>@enderror
                </div>
                <div class="eob-group">
                    <label class="eob-label">Vendor Name</label>
                    <input type="text" name="vendor_name" class="eob-input" value="{{ old('vendor_name', $asset?->vendor_name) }}">
                    @error('vendor_name')<div class="eob-error">{{ $message }}</div>@enderror
                </div>
                <div class="eob-group">
                    <label class="eob-label">Invoice Number</label>
                    <input type="text" name="invoice_number" class="eob-input" value="{{ old('invoice_number', $asset?->invoice_number) }}">
                    @error('invoice_number')<div class="eob-error">{{ $message }}</div>@enderror
                </div>
                <div class="eob-group">
                    <label class="eob-label">Warranty Expiry Date</label>
                    <input type="date" name="warranty_expiry_date" class="eob-input" value="{{ old('warranty_expiry_date', optional($asset?->warranty_expiry_date)->format('Y-m-d')) }}">
                    @error('warranty_expiry_date')<div class="eob-error">{{ $message }}</div>@enderror
                </div>
                <div class="eob-group">
                    <label class="eob-label">Assigned Employee</label>
                    <select name="assigned_employee_id" class="eob-select" id="assetAssignedEmployeeGroup">
                        <option value="">Select employee</option>
                        @foreach($employees as $employee)
                            <option value="{{ $employee->id }}" @selected((string) old('assigned_employee_id', $asset?->assigned_employee_id) === (string) $employee->id)>
                                {{ $employee->employee_id }} - {{ $employee->name }}
                            </option>
                        @endforeach
                    </select>
                    @error('assigned_employee_id')<div class="eob-error">{{ $message }}</div>@enderror
                </div>
                <div class="eob-group" id="assetAssignedDateGroup">
                    <label class="eob-label">Assigned Date</label>
                    <input type="date" name="assigned_date" class="eob-input" value="{{ old('assigned_date', optional($asset?->assigned_date)->format('Y-m-d')) }}">
                    @error('assigned_date')<div class="eob-error">{{ $message }}</div>@enderror
                </div>
                <div class="eob-group full">
                    <label class="eob-label">Condition Notes</label>
                    <textarea name="condition_notes" class="eob-textarea">{{ old('condition_notes', $asset?->condition_notes) }}</textarea>
                    @error('condition_notes')<div class="eob-error">{{ $message }}</div>@enderror
                </div>
                <div class="eob-group full">
                    <label class="eob-label">Description</label>
                    <textarea name="description" class="eob-textarea">{{ old('description', $asset?->description) }}</textarea>
                    @error('description')<div class="eob-error">{{ $message }}</div>@enderror
                </div>
            </div>
        </div>

        <div class="eob-foot">
            <a href="{{ $cancelRoute }}" class="eob-btn eob-btn-ghost">Cancel</a>
            <button type="submit" class="eob-btn eob-btn-primary">{{ $submitLabel }}</button>
        </div>
    </form>
</div>

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function () {
    const statusSelect = document.getElementById('assetStatusSelect');
    const assignedEmployeeField = document.getElementById('assetAssignedEmployeeGroup');
    const assignedDateGroup = document.getElementById('assetAssignedDateGroup');

    function syncAssignedFields() {
        const isAssigned = statusSelect && statusSelect.value === 'assigned';

        if (assignedEmployeeField) {
            assignedEmployeeField.disabled = !isAssigned;
            if (!isAssigned) {
                assignedEmployeeField.value = '';
            }
        }

        if (assignedDateGroup) {
            assignedDateGroup.style.opacity = isAssigned ? '1' : '.55';
            const dateInput = assignedDateGroup.querySelector('input');
            if (dateInput) {
                dateInput.disabled = !isAssigned;
                if (!isAssigned) {
                    dateInput.value = '';
                }
            }
        }
    }

    statusSelect?.addEventListener('change', syncAssignedFields);
    syncAssignedFields();
});
</script>
@endpush
